# Generated by Django 6.0 on 2025-12-24 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listitem',
            name='notification_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='listitem',
            name='notification_repeat',
            field=models.BooleanField(default=False),
        ),
    ]
