# Generated by Django 6.0 on 2025-12-24 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_listitem_notification_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listitem',
            old_name='is_prioruty',
            new_name='is_priority',
        ),
    ]
