# Generated by Django 6.0 on 2025-12-24 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_rename_is_prioruty_listitem_is_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listitem',
            name='detail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
